### ISSUE TITLE
AttributeError: module 'six.moves' has no attribute 'collections_abc'

### ISSUE THREAD

**Issue by GoekhanA** [jonnekaunisto/simple-youtube-api#37]
Hey, im getting this error while uploading, uploads worked fine a couple days ago.

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "twitch.py", line 112, in Download
    self.Render()
  File "twitch.py", line 131, in Render
    self.Upload()
  File "twitch.py", line 138, in Upload
    channel.login("./Channel/client_secret.json", "./Channel/credentials.storage")
  File "/usr/local/lib/python3.7/dist-packages/simple_youtube_api/Channel.py", line 87, in login
    API_SERVICE_NAME, API_VERSION, credentials=credentials
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery.py", line 288, in build
    adc_key_path=adc_key_path,
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/googleapiclient/discovery.py", line 466, in build_from_document
    if isinstance(client_options, six.moves.collections_abc.Mapping):
AttributeError: module 'six.moves' has no attribute 'collections_abc'

```

**Comment by GoekhanA** [comment]
```pip install --upgrade six``` Fixes the problem
