### ISSUE TITLE
Progress Bar throwing error and halting upload

### ISSUE THREAD

**Issue by bhattarai333** [jonnekaunisto/simple-youtube-api#65]
The upload works mostly fine, but at the last moment the value goes larger than the progress bar and throws an error and stops the whole upload, very frustrating.

```
Traceback (most recent call last):
  File "/hdd/Projects/VideoBook/upload.py", line 61, in upload_API
    video = channel.upload_video(video)
  File "/home/bhattarai/.local/lib/python3.9/site-packages/simple_youtube_api/Channel.py", line 120, in upload_video
    youtube_video = initialize_upload(self.channel, video)
  File "/home/bhattarai/.local/lib/python3.9/site-packages/simple_youtube_api/Channel.py", line 201, in initialize_upload
    return resumable_upload(insert_request)
  File "/home/bhattarai/.local/lib/python3.9/site-packages/simple_youtube_api/Channel.py", line 227, in resumable_upload
    bar.update(100 * 10 * status.progress() + 1)
  File "/home/bhattarai/.local/lib/python3.9/site-packages/progressbar/bar.py", line 934, in update
    raise ValueError(
ValueError: Value 1000.1275017603614 is too large. Should be between 0 and 1000

```

**Comment by bhattarai333** [comment]
Just realized this has been fixed and my version is out of date, closing
